#!/usr/bin/env python3
"""Render the human catalog index from canonical catalog data."""

from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import Any

from scripts.catalog_entries import entry_type, load_taxonomy, project_entry
from scripts.catalog_validation import load_manifest

INDEX_RELATIVE_PATH = Path("catalog/index.md")


def _link_for(asset: dict[str, Any]) -> str:
    entrypoints = asset.get("entrypoints")
    if isinstance(entrypoints, list) and entrypoints:
        return f"../{entrypoints[0]}"
    external_links = asset.get("external_links")
    if isinstance(external_links, list) and external_links:
        return external_links[0]
    return "manifest.json"


def _row(asset: dict[str, Any]) -> str:
    entry = asset["entry"]
    topics = ", ".join(f"`{topic}`" for topic in entry["topics"]) or "—"
    install = asset.get("install")
    mode = install.get("mode") if isinstance(install, dict) else "—"
    return (
        f"| [`{asset['id']}`]({_link_for(asset)}) | {entry['why']} | "
        f"{topics} | {asset['maturity']} | {mode} |"
    )


def render_index(root: Path) -> str:
    """Return deterministic Markdown for the current manifest and taxonomy."""

    manifest = load_manifest(root)
    taxonomy = load_taxonomy(root)
    raw_assets = manifest.get("assets", [])
    assets = sorted(
        (
            project_entry(asset, taxonomy)
            for asset in raw_assets
            if isinstance(asset, dict)
        ),
        key=lambda item: item.get("id", ""),
    )
    counts = Counter(asset["entry"]["type"] for asset in assets)
    lines = [
        "<!-- Generated by python3 scripts/workbench.py index --write. Do not edit by hand. -->",
        "# Multiplier catalog",
        "",
        "A **multiplier** is anything in this repository that makes agent work more",
        "capable, repeatable, or trustworthy. An **entry** is its machine-readable",
        "catalog record. The [manifest](manifest.json) owns inventory and runtime",
        "facts; the [taxonomy](taxonomy.json) owns types and curated collections.",
        "",
        "## Browse by type",
        "",
        "| Type | Use it for | Entries |",
        "| --- | --- | ---: |",
    ]
    types = taxonomy.get("types", [])
    for item in types:
        if not isinstance(item, dict):
            continue
        lines.append(
            f"| {item['label']} | {item['purpose']} | {counts[item['id']]} |"
        )

    topic_counts = Counter(
        topic for asset in assets for topic in asset["entry"]["topics"]
    )
    lines.extend(
        [
            "",
            "## Browse by topic or use case",
            "",
            "Topics are many-to-many metadata, so one multiplier can appear in several",
            "ways of browsing without being duplicated on disk.",
            "",
            "| Topic | Entries | Browse |",
            "| --- | ---: | --- |",
        ]
    )
    common_topics = sorted(
        ((topic, count) for topic, count in topic_counts.items() if count > 1),
        key=lambda item: (-item[1], item[0]),
    )[:24]
    for topic, count in common_topics:
        lines.append(
            f"| `{topic}` | {count} | `python3 scripts/workbench.py list --topic {topic}` |"
        )
    lines.extend(
        [
            "",
            "The table shows the most common topics. Use `list --topic <slug>` or",
            "`search --query <words>` for the long tail without growing this page",
            "linearly with every tag.",
        ]
    )

    by_id = {asset["id"]: asset for asset in assets}
    for collection in taxonomy.get("collections", []):
        if not isinstance(collection, dict):
            continue
        lines.extend(
            [
                "",
                f"## {collection['title']}",
                "",
                collection["summary"],
                "",
                "| Multiplier | Why open it | Type |",
                "| --- | --- | --- |",
            ]
        )
        for asset_id in collection.get("entries", []):
            asset = by_id.get(asset_id)
            if asset is None:
                continue
            lines.append(
                f"| [`{asset_id}`]({_link_for(asset)}) | {asset['entry']['why']} | "
                f"{asset['entry']['type']} |"
            )

    for type_item in types:
        if not isinstance(type_item, dict):
            continue
        type_assets = [
            asset
            for asset in assets
            if entry_type(asset, taxonomy) == type_item["id"]
        ]
        if not type_assets:
            continue
        lines.extend(
            [
                "",
                f"## {type_item['label']}",
                "",
                type_item["purpose"],
                "",
                "| Multiplier | Why open it | Topics | Maturity | Adoption |",
                "| --- | --- | --- | --- | --- |",
            ]
        )
        lines.extend(_row(asset) for asset in type_assets)

    lines.extend(
        [
            "",
            "## Inspect or adopt one",
            "",
            "```bash",
            "python3 scripts/workbench.py show <entry-id> --json",
            "python3 scripts/workbench.py install <entry-id> \\",
            "  --target generic --root /tmp/workbench-target --dry-run --json",
            "```",
            "",
            "See the [catalog model](../docs/catalog-model.md) before adding an entry",
            "and the [workbench manual](../docs/workbench.md) for setup, overlays,",
            "promotion admission, validation, and safety boundaries.",
            "",
        ]
    )
    return "\n".join(lines)


def validate_index(root: Path) -> list[str]:
    """Report whether the checked-in index matches canonical catalog data."""

    path = root / INDEX_RELATIVE_PATH
    if not path.is_file():
        return ["catalog/index.md: missing generated index"]
    if path.read_text(encoding="utf-8") != render_index(root):
        return [
            "catalog/index.md: generated index is stale; run "
            "python3 scripts/workbench.py index --write"
        ]
    return []
